### ISSUE TITLE
Gender Dif

### ISSUE THREAD

**Issue by LCisannoyed** [markdly/conquestr#30]
cqc_Show to read in the gender result. 
I need item index, Chi Sqr results, and if item favours a gender

**Comment by markdly** [comment]
`cq_show()` is now flexible enough to import tables from show files when a dif analysis was requested (e.g. model: item + gender + item*gender). Added in 7994b3768e26acf1be4ac20821da66ba7f564deb

Example usage:

``` r
library(conquestr)
x <- system.file("extdata", "dif.shw", package = "conquestr")
df <- cq_show(x, fit = FALSE)
df
#> # A tibble: 3 x 2
#>   term     data              
#>   <chr>    <list>            
#> 1 grp      <tibble [2 × 13]> 
#> 2 item     <tibble [20 × 13]>
#> 3 item*grp <tibble [40 × 15]>

df$data[[1]]
#> # A tibble: 2 x 13
#>   grp_index   grp    est   err uw_mnsq uw_ci_lo uw_ci_hi  uw_t  mnsq ci_lo
#>       <int> <int>  <dbl> <dbl>   <dbl>    <dbl>    <dbl> <dbl> <dbl> <dbl>
#> 1         1     1  0.258 0.019    1        0.88     1.12   0    1     0.88
#> 2         2     2 -0.258 0.019    1.04     0.88     1.12   0.7  1.04  0.88
#> # ... with 3 more variables: ci_hi <dbl>, t <dbl>, section_index <chr>
```

Created on 2018-09-12 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I think the other features such as labelling for 'favouring' etc are not really a good fit for conquestr at this stage. E.g. the 'rules' are likely to change depending on the context so I'm inclined to leave those out for now (and implement on a project basis instead). Let me know if you feel strongly otherwise though! 😄
